# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNativeDeviceInfoExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeDeviceInfoExample
  
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'reactNativeDeviceInfoExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativeDeviceInfoExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeDeviceInfoExample-tvOS

  target 'reactNativeDeviceInfoExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
